### ISSUE TITLE
Can I rotate the scene while running scripts?

### ISSUE THREAD

**Issue by anzisheng** [yanchxx/CDBA#19]
Hi, I'm able to run to demo with blender now, but it turns out that the view is locked while the script is running.

If there's a way to enable rotation?

**Comment by yanchxx** [comment]
From my understanding of Blender Python's `modal` function, it should be rotatable while running script. 

But I remember when I ran the script it can't rotate.

I am too busy to modify this feature recently. I will modify it later when I have time.

**Comment by yanchxx** [comment]
For the first question of your last issue, I will also update it when I have time to make use of the automatic binding of Mixamo so that you can use any pre-build model.

For camera, check out the Blender website or find a tutorial to see how to set up the camera.

**Comment by anzisheng** [comment]
Thx a lot~ 

I figured out how to setup camera position and orientation now. 

I will do some research about rotating the scene as well. Gonna update you if got any findings.

**Comment by yanchxx** [comment]
I tried to make the view to rotate while the script was running, but in some cases it would stall or even crash. So I still made it impossible for the script to rotate the view while it was running.

Mainly because Blender Python doesn't support multiple processes very well (or I can't figure out how to run multiple processes), it tends to stall.
