### ISSUE TITLE
multiple people

### ISSUE THREAD

**Issue by zhangby2085** [yanchxx/CDBA#25]
Hey, yanch2116, very impressive job done in visualizing 3D characters. I tested and it works, one question to ask, the code romp_server.py has the setting.show_largest=True, I am thinking, what is the condition with multiple people in the webcamera, when there are many people, the blender character keeps on shifting. Are they ways to solve this?
1, keep on the object tracker in single object_ID
2, visualize multiple 3D characters as input in the camera

**Comment by yanchxx** [comment]
It's a little cumbersome to implement these programming in Blender, and it's troublesome for users to place multiple people. At present, I just want to make a demo in blender. 

In fact, I have made a web multiplayer chatroom using ROMP, which can drive multiple 3D characters with one camera and see the 3D characters of others in the chatroom, using object tracker.

You can visit through https://www.yanch.cloud or check the [demo paper](http://arxiv.org/abs/2209.00776) if you are interested.

Sometimes the web is inaccessible, because I may be doing some development.

**Comment by zhangby2085** [comment]
Thank you for the information, yanch2116, it helps a lot, the url is not working (This site can’t be reached), and the paper's idea of chat room 3D virtual avatars is brilliant. What do you think of the ROMP, can not only the texture (single color) be changed but also the characters, like the changing of armature 3d model .fbx, be applied directly in ROMP, without using blender?

**Comment by yanchxx** [comment]
It sounds good to use some python libraries directly to render different 3D characters without using Blender. 

In fact, I implemented it with the author of ROMP before, but because we didn't know how to use multiple 3D characters at that time, we continued to use SMPL of different textures.

When I am free, I may realize this idea. Thank you.
